name: Update Submodules Periodically

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Update submodules
      run: |
        git submodule update --remote --recursive

    - name: Configure Git
      run: |
        git config --global user.email "sscott@govanguard.com"
        git config --global user.name "sscottgvit"

    - name: Commit and push if changes
      run: |
        git add .
        git diff-index --quiet HEAD || git commit -m "Update submodules"
        git push
