name: Update Submodules Periodically

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Update submodules
      run: |
        git submodule update --remote --recursive

    - name: Configure Git
      run: |
        git config --global user.email "sscott@govanguard.com"
        git config --global user.name "sscottgvit"

    - name: Generate submodule info for README.md
      run: |
        echo "# Gotham Security Aggregate Repository - Submodule Information" > README.md
        git submodule foreach 'echo "- **${name}**: Version: $(git describe --tags --always --dirty), Description: $(git log -1 --pretty=format:"%s")" >> "$GITHUB_WORKSPACE/submodule_info.md"'

    - name: Append submodule info to README.md
      run: |
        if [ -f "$GITHUB_WORKSPACE/submodule_info.md" ]; then
          cat "$GITHUB_WORKSPACE/submodule_info.md" >> README.md
          rm "$GITHUB_WORKSPACE/submodule_info.md"
        else
          echo "No submodule information file found."
        fi
      shell: /usr/bin/bash -e {0}


    - name: Commit and push if changes
      run: |
        git add .
        git diff-index --quiet HEAD || git commit -m "Update submodules"
        git push
